app/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('doacoes/', views.doacoes_view, name='doacoes'),
    path('doacoes/<int:doacao_id>/', views.buscar_dados_doacao, name='realizar_doacao'),
    path('doacoes/cadastrar-doacao/', views.cadastrar_doacao, name='cadastrar_doacao'),
    path('doacoes/<int:doacao_id>/detalhar-doacao', views.detalhar_doacao, name='detalhar_doacao'),
    path('doacoes/<int:doacao_id>/editar-doacao/', views.editar_doacao, name='editar_doacao'),
    path('doacoes/<int:doacao_id>/excluir-doacao/', views.excluir_doacao, name='excluir_doacao'),
    path('necessidades/', views.necessidades_view, name='necessidades'),
    path('necessidades/<int:necessidade_id>/', views.buscar_dados_necessidade, name='realizar_doacao'),
    path('necessidades/cadastrar-necessidade/', views.cadastrar_necessidade, name='cadastrar_necessidade'),
    path('necessidades/<int:necessidade_id>/detalhar-necessidade', views.detalhar_necessidade, name='detalhar_necessidade'),
    path('necessidades/<int:necessidade_id>/editar-necessidade/', views.editar_necessidade, name='editar_necessidade'),
    path('necessidades/<int:necessidade_id>/excluir-necessidade/', views.excluir_necessidade, name='excluir_necessidade'),
    path('cadastrar-item/', views.cadastrar_item, name='cadastrar_item'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls")),
]

app/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models

class UsuarioManager(BaseUserManager):
    def create_user(self, username, email, password=None, tipo_usuario=None, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(username=username, email=email, tipo_usuario=tipo_usuario, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password=None, tipo_usuario=None, **extra_fields):
        tipo_usuario, created = TipoUsuario.objects.get_or_create(nome="Administrador")
        
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(username, email, password, tipo_usuario=tipo_usuario,**extra_fields)

class TipoUsuario(models.Model):
    class Meta:
        verbose_name = "Tipo de usuário"
        verbose_name_plural = "Tipos de usuários"

    nome = models.CharField(max_length=255, unique=True, verbose_name="Nome")

    def __str__(self):
        return self.nome

class Usuario(AbstractUser):
    class Meta:
        verbose_name = "Usuário"
        verbose_name_plural = "Usuários"

    tipo_usuario = models.ForeignKey(TipoUsuario, on_delete=models.CASCADE, verbose_name="Tipo de usuário")
    telefone = models.CharField(max_length=11, null=True, blank=True, verbose_name='Telefone')
    objects = UsuarioManager()

    def __str__(self):
        return self.username
    
class CategoriaItem(models.Model):
    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"

    nome = models.CharField(max_length=255, unique=True, verbose_name="Nome")

    def __str__(self):
        return self.nome    
    
class Item(models.Model):   
    class Meta:
        verbose_name = "Item"
        verbose_name_plural = "Itens"

    STATUS_CHOICES = [
        ('Disponível', 'Disponível'),
        ('Doado', 'Doado'),
    ]

    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='itens', verbose_name="Usuário")
    nome = models.CharField(max_length=255, verbose_name="Nome")
    categoria = models.ForeignKey(CategoriaItem, on_delete=models.CASCADE, verbose_name="Categoria")
    descricao = models.TextField(verbose_name="Descrição")
    data_disponibilidade = models.DateTimeField(auto_now_add=True, verbose_name="Data de disponibilidade")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Disponível', verbose_name="Status")

    def __str__(self):
        return self.nome

class Doacao(models.Model):
    class Meta:
        verbose_name = "Doação"
        verbose_name_plural = "Doações"

    ESTADO_CONSERVACAO_CHOICES = [
        ('Novo', 'Novo'),
        ('Usado', 'Usado'),
        ('Bom', 'Bom'),
        ('Ruim', 'Ruim'),
    ]

    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='doacoes', verbose_name="Usuário")
    item = models.ForeignKey(Item, on_delete=models.CASCADE, verbose_name="Item")
    descricao = models.TextField(verbose_name="Descrição")
    estado_conservacao = models.CharField(max_length=20, choices=ESTADO_CONSERVACAO_CHOICES, verbose_name="Estado de conservação")
    status = models.CharField(max_length=20, choices=Item.STATUS_CHOICES, default='Disponível', verbose_name="Status")
    data_doacao = models.DateTimeField(auto_now_add=True, verbose_name="Data de doação")

    def __str__(self):
        return f"{self.usuario} - {self.item}"

class Necessidade(models.Model):
    class Meta:
        verbose_name = "Necessidade"
        verbose_name_plural = "Necessidades"

    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='necessidades', verbose_name="Usuário")
    item = models.ForeignKey(Item, on_delete=models.CASCADE, verbose_name="Item")
    descricao = models.TextField(verbose_name="Descrição")
    quantidade = models.PositiveIntegerField(verbose_name="Quantidade")
    aprovado_por_admin = models.BooleanField(default=False, verbose_name="Aprovado por administrador")
    status = models.CharField(max_length=20, choices=Item.STATUS_CHOICES, default='Disponível', verbose_name="Status")
    data_necessidade = models.DateTimeField(auto_now_add=True, verbose_name="Data de necessidade")

    def __str__(self):
        return f"{self.usuario} - {self.item} - {self.quantidade}"

app/templates/pages/detalhes_doacao.html
{% extends "base/base.html" %}

{% block content %}
<div class="container mt-4">
    <h2>Detalhes da Doação</h2>
    
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Informações da Doação</h5>
            <p><strong>Item:</strong> {{ doacao.item.nome }}</p>
            <p><strong>Descrição:</strong> {{ doacao.descricao }}</p>
            <p><strong>Estado de Conservação:</strong> {{ doacao.estado_conservacao }}</p>
            <p><strong>Status:</strong> {{ doacao.status }}</p>
        </div>
    </div>

    <div class="card mt-3">
        <div class="card-body">
            <h5 class="card-title">Informações do Doador</h5>
            <p><strong>Email:</strong> {% if doador.email %}{{ doador.email }}{% else %}-{% endif %}</p>
            <p><strong>Telefone: </strong>{% if doador.telefone %}{{ doador.telefone }}{% else %}-{% endif %}</p>
            <p><strong>Usuário:</strong> {{ doador.username }}</p>
        </div>
    </div>

    <a href="{% url 'doacoes' %}" class="btn btn-secondary mt-3">Voltar</a>
</div>
{% endblock %}

app/templates/pages/detalhes_necessidade.html
{% extends "base/base.html" %}

{% block content %}
<div class="container mt-4">
    <h2>Detalhes da Necessidade</h2>
    
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Informações da Necessidade</h5>
            <p><strong>Item:</strong> {{ necessidade.item.nome }}</p>
            <p><strong>Descrição:</strong> {{ necessidade.descricao }}</p>
            <p><strong>Quantidade:</strong> {{ necessidade.quantidade }}</p>
            <p><strong>Status:</strong> {{ necessidade.status }}</p>
        </div>
    </div>

    <div class="card mt-3">
        <div class="card-body">
            <h5 class="card-title">Informações do Necessitante</h5>
            <p><strong>Email:</strong> {% if necessitante.email %}{{ necessitante.email }}{% else %}-{% endif %}</p>
            <p><strong>Telefone: </strong>{% if necessitante.telefone %}{{ necessitante.telefone }}{% else %}-{% endif %}</p>
            <p><strong>Usuário:</strong> {{ necessitante.username }}</p>
        </div>
    </div>

    <a href="{% url 'necessidades' %}" class="btn btn-secondary mt-3">Voltar</a>
</div>
{% endblock %}

app/templates/pages/doacoes.html
{% extends "base/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<div class="d-flex flex-column flex-md-row justify-content-start my-3 gap-3">
    <!-- Botões para abrir os modais -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createDoacaoModal">
        <i class="fas fa-plus me-1"></i>
        Adicionar Doação
    </button>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createItemModal">
        <i class="fas fa-plus me-1"></i>
        Adicionar Item
    </button>
</div>

<!-- Modal de adicionar doação -->
<div class="modal fade" id="createDoacaoModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="createDoacaoModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form action="{% url 'cadastrar_doacao' %}" method="post" class="needs-validation" novalidate>
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="createDoacaoModalLabel">Adicionar Doação</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    {{ add_doacao_form|crispy }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-primary">Adicionar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal de adicionar item -->
<div class="modal fade" id="createItemModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="createItemModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form action="{% url 'cadastrar_item' %}" method="post" class="needs-validation" novalidate>
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="createItemModalLabel">Adicionar Item</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    {{ item_form|crispy }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-primary">Adicionar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal de edição de doação -->
<div class="modal fade" id="editDoacaoModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="editDoacaoModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form action="" method="post" id="editDoacaoForm" class="needs-validation" novalidate>
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="editDoacaoModalLabel">Editar Doação</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    {{ edit_doacao_form|crispy }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-primary">Salvar Alterações</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal de exclusão de doação -->
<div class="modal fade" id="deleteDoacaoModal" tabindex="-1" aria-labelledby="deleteDoacaoModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteDoacaoModalLabel">Excluir Doação</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Tem certeza que deseja excluir esta doação?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <form action="" id="deleteDoacaoForm" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Excluir</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Tabela de Doações -->
<div class="table-container mt-4">
    <table class="table align-middle">
        <caption>Lista de Doações</caption>
        <thead class="text-center">
            <tr>
                <th scope="col">#</th>
                <th scope="col">ID</th>
                <th scope="col">Item</th>
                <th scope="col">Descrição</th>
                <th scope="col">Estado de Conservação</th>
                <th scope="col">Status</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody class="text-center table-group-divider" id="tableBody">
            {% for doacao in doacoes %}
            <tr>
                <td scope="row">{{ forloop.counter }}</td>
                <td>{{ doacao.id }}</td>
                <td>{{ doacao.item.nome }}</td>
                <td>{{ doacao.descricao }}</td>
                <td>{{ doacao.estado_conservacao }}</td>
                <td>{{ doacao.status }}</td>
                <td>
                    <a href="{% url 'detalhar_doacao' doacao.id %}" class="btn btn-info btn-sm">
                        <i class="fas fa-eye"></i> Detalhes
                    </a>
                    {% if user.tipo_usuario.nome == "Administrador" or user == doacao.usuario %}
                    <button type="button" class="btn btn-warning btn-sm update-doacao" data-bs-toggle="modal"
                        data-bs-target="#editDoacaoModal" data-doacao-id="{{ doacao.id }}">
                        <i class="fas fa-edit ms-1"></i>
                        Editar
                    </button>
                    <button type="button" class="btn btn-danger btn-sm delete-doacao" data-bs-toggle="modal"
                        data-bs-target="#deleteDoacaoModal" data-doacao-id="{{ doacao.id }}">
                        <i class="fas fa-trash-alt ms-1"></i>
                        Excluir
                    </button>
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr class="null">
                <td colspan="7" class="text-center">Nenhuma doação encontrada</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

{% block scripts %}
<script>
    document.addEventListener("DOMContentLoaded", function () {
        // Lógica de editar doação
        const editModal = document.getElementById('editDoacaoModal');
        const editForm = document.getElementById('editDoacaoForm');

        editModal.addEventListener('show.bs.modal', function (event) {
            const button = event.relatedTarget;
            let doacaoId = button.getAttribute('data-doacao-id');
            editForm.action = `/doacoes/${doacaoId}/editar-doacao/`;

            fetch(`/doacoes/${doacaoId}/`)
                .then(response => response.json())
                .then(data => {
                    $('#editDoacaoForm #id_item').val(data.item);
                    $('#editDoacaoForm #id_descricao').val(data.descricao);
                    $('#editDoacaoForm #id_estado_conservacao').val(data.estado_conservacao);
                    $('#editDoacaoForm #id_status').val(data.status);
                });

            editForm.addEventListener('submit', function (event) {
                event.preventDefault();
                fetch(editForm.action, {
                    method: 'POST',
                    body: new FormData(editForm),
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}'
                    }
                })
                    .then(response => response.json())
                    .then(data => {
                        if (data.success) {
                            window.location.reload();
                        } else {
                            alert('Erro ao editar doação');
                        }
                    });
            });
        });

        // Exibir modal de excluir doação
        document.querySelectorAll('button[data-doacao-id]').forEach(button => {
            button.addEventListener('click', function() {
                const doacaoId = this.getAttribute('data-doacao-id');
                const form = document.getElementById('deleteDoacaoForm');
                form.action = `/doacoes/${doacaoId}/excluir-doacao/`;
            });
        });
    });
</script>
{% endblock scripts %}

app/templates/pages/index.html
{% extends "base/base.html" %}

{% block content %}
<header class="bg-light text-center p-5">
    <h1>Facilitamos sua Doação!</h1>
    <p>Cadastre suas doações e conecte-se a instituições que precisam de sua ajuda..</p>

    <a href="{% url 'login' %}" class="btn btn-primary mt-2">Fazer Login</a>
    <a href="{% url 'register' %}" class="btn btn-success mt-2">Criar uma conta</a>
   
</header>
{% endblock content %}

app/templates/pages/login.html
{% extends 'base/base.html' %}

{% load crispy_forms_tags %}

{% block title %} Entrar {% endblock title %}

{% block styles %}
<style>
    html,
    body {
        height: 100%;
    }

    .form-signin {
        max-width: 500px;
        padding: 1rem;
    }
</style>
{% endblock styles %}

{% block content %}
<main class="form-signin w-100 m-auto">
    <h1>Entrar</h1>

    <form action="{% url 'login' %}" method="post" class="needs-validation" autocomplete="off" novalidate>
        {% csrf_token %}

        {{ form|crispy }}

        <div class="d-flex flex-column justify-content-center">
            <button type="submit" class="btn btn-primary">Entrar</button>
            <a href="{% url 'register' %}" class="btn btn-link mt-2">Criar uma conta</a>
        </div>
    </form>
</main>
{% endblock content %}

app/templates/pages/necessidades.html
{% extends "base/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<div class="d-flex flex-column flex-md-row justify-content-start my-3 gap-3">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createNecessidadeModal">
        <i class="fas fa-plus me-1"></i>
        Adicionar Necessidade
    </button>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createItemModal">
        <i class="fas fa-plus me-1"></i>
        Adicionar Item
    </button>
</div>

<!-- Modal de adicionar necessidade -->
<div class="modal fade" id="createNecessidadeModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="createNecessidadeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form action="{% url 'cadastrar_necessidade' %}" method="post" id="createNecessidadeForm" class="needs-validation" novalidate>
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="createNecessidadeModalLabel">Adicionar Necessidade</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    <!-- Formulário de Necessidade -->
                    {{ add_necessidade_form|crispy }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-primary">Adicionar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal de adicionar item -->
<div class="modal fade" id="createItemModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="createItemModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form action="{% url 'cadastrar_item' %}" method="post" id="createItemForm" class="needs-validation" novalidate>
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="createItemModalLabel">Adicionar Item</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    {{item_form|crispy}}
               </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-primary">Adicionar</button>
                </div> 
            </form>
        </div>
    </div>
 </div>

<!-- Modal de edição de necessidade -->
<div class="modal fade" id="editNecessidadeModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="editNecessidadeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form action="" method="post" id="editNecessidadeForm" class="needs-validation" novalidate>
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="editNecessidadeModalLabel">Editar Necessidade</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    {{ edit_necessidade_form|crispy }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-primary">Salvar Alterações</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal de exclusão de necessidade -->
<div class="modal fade" id="deleteNecessidadeModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="deleteNecessidadeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deleteNecessidadeModalLabel">Excluir Necessidade</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Tem certeza que deseja excluir esta necessidade?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <form action="" method="post" id="deleteNecessidadeForm">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Excluir</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Tabela de Necessidades -->
<div class="table-container mt-4">
    <table class="table align-middle">
        <caption>Lista de Necessidades</caption>
        <thead class="text-center">
            <tr>
                <th scope="col">#</th>
                <th scope="col">ID</th>
                <th scope="col">Item Necessário</th>
                <th scope="col">Descrição</th>
                <th scope="col">Status</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody class="text-center table-group-divider" id="tableBody">
            {% for necessidade in necessidades %}
            <tr>
                <td scope="row">{{ necessidade.id }}</td>
                <td scope="row">{{ necessidade.id }}</td>
                <td scope="row">{{ necessidade.item.nome }}</td>
                <td scope="row">{{ necessidade.descricao }}</td>
                <td scope="row">{{ necessidade.status }}</td>
                <td scope="row">
                    <a href="{% url 'detalhar_necessidade' necessidade.id %}" class="btn btn-primary btn-sm">
                        <i class="fas fa-eye"></i> 
                        Detalhes
                    </a>
                    {% if user == necessidade.usuario or user.tipo_usuario.nome == "Administrador"%}
                    <button type="button" class="btn btn-warning btn-sm update-necessidade" data-bs-toggle="modal" data-bs-target="#editNecessidadeModal" data-necessidade-id="{{ necessidade.id }}">
                        <i class="fas fa-edit"></i>
                        Editar
                    </button>
                    <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteNecessidadeModal" data-necessidade-id="{{ necessidade.id }}">
                        <i class="fas fa-trash"></i>
                        Excluir
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr class="null">
                <td colspan="6" class="text-center">Nenhuma necessidade encontrada</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

{% block scripts %}
<script>
    // Lógica de editar necessidade
    const editModal = document.getElementById('editNecessidadeModal');
    const editForm = document.getElementById('editNecessidadeForm');

    editModal.addEventListener('show.bs.modal', function(event) {
        const button = event.relatedTarget;
        const necessidadeId = button.getAttribute('data-necessidade-id');
        editForm.action = `/necessidades/${necessidadeId}/editar-necessidade/`;

        fetch(`/necessidades/${necessidadeId}/`)
            .then(response => response.json())
            .then(data => {
                $('#editNecessidadeForm #id_item').val(data.item);
                $('#editNecessidadeForm #id_descricao').val(data.descricao);
                $('#editNecessidadeForm #id_quantidade').val(data.quantidade);
                $('#editNecessidadeForm #id_status').val(data.status);
            });

        editForm.addEventListener('submit', function(event) {
            event.preventDefault();
            const formData = new FormData(editForm);
            fetch(editForm.action, {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}'
                }
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    window.location.reload();
                } else {
                    alert('Erro ao editar necessidade');
                }
            });
        });
    });
    
    // Exibir modal de excluir necessidade
    document.querySelectorAll('button[data-necessidade-id]').forEach(button => {
        button.addEventListener('click', function() {
            const necessidadeId = this.getAttribute('data-necessidade-id');
            const form = document.getElementById('deleteNecessidadeForm');
            form.action = `/necessidades/${necessidadeId}/excluir-necessidade/`;
        });
    });
</script>
{% endblock scripts %}

app/templates/pages/register.html
{% extends 'base/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Cadastre-se{% endblock title %}

{% block styles %}
<style>
    html,
    body {
        height: 100%;
    }

    .form-signin {
        max-width: 500px;
        padding: 1rem;
    }
</style>
{% endblock styles %}

{% block content %}
<main class="form-signin w-100 m-auto">
    <h1>Criar Conta</h1>

    <form action="{% url 'register' %}"" method="post" class="needs-validation" autocomplete="off" novalidate>
        {% csrf_token %}

        {{ form|crispy }}

        <div class="d-flex flex-column justify-content-center">
            <button type="submit" class="btn btn-primary">Criar Conta</button>
            <a href="{% url 'login' %}" class="btn btn-link mt-2">Já tem uma conta? Entre aqui</a>
        </div>
    </form>
</main>
{% endblock content %}